### ISSUE TITLE
Results pane broken since Sublime build 4166

### ISSUE THREAD

**Issue by shuckc** [komsit37/sublime-q#38]
Since ST3 build 4166 query results no longer show in the results/build output box when pressing `Cmd + Enter`. The status bar correctly shows the shape of the results, and the query executes fine. 
Popup `Cmd + e` and phantom `Cmd + Shift + Enter` results panes still work OK.
Release notes at https://www.sublimetext.com/download

<img width="575" alt="image" src="https://github.com/komsit37/sublime-q/assets/1188286/c44c2bf8-c286-409e-9e1c-29338b9761ee">

In the sublime console [this message is shown](https://github.com/komsit37/sublime-q/blob/master/q_chain.py#L19):

    >>> 
    init localhost:8885
    init localhost:8885

    break chain because output is none

**Comment by atf1206** [comment]
`panel.insert(edit, panel.size(), input)`

seems to no longer be working. I am not sure why; it appears that 

`panel.run_command("append", {"characters": input})`

will work instead. Opened a pull request -- I have not had the chance to look into this further, so maybe there is a better fix; hopefully this will at least save someone some time troubleshooting.

**Comment by komsit37** [comment]
Thanks for the report and the fix! I have merged and released the fix in 1.4.0.
