### ISSUE TITLE
toggle comment is not working on this plugin

### ISSUE THREAD

**Issue by semkilljaeden** [komsit37/sublime-q#8]

**Comment by komsit37** [comment]
Hi, can you give me an example of the issue?

**Comment by semkilljaeden** [comment]
When syntax is set to be q, after I select a block of codes, press Ctrl+ /, the code won't be  comment out. This hot key works fine under other syntax such as c. 

Get Outlook for iOS

On Wed, May 11, 2016 at 8:58 PM -0700, "komsit37" notifications@github.com wrote:

Hi, can you give me an example of the issue?

**Comment by komsit37** [comment]
this is not supported
